name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    tags: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.yaml

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Check Code Formatting (Spotless & Sortpom)
      run: mvn spotless:check sortpom:verify

    - name: Build with Maven (including Tests)
      run: mvn -B verify

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: test-reports
        path: target/surefire-reports/
        retention-days: 5

    - name: Upload Coverage Report
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: coverage-report
        path: target/site/jacoco/
        retention-days: 5
